[package]
name = "hosting_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bollard = "0.13.0"
actix-web = "4"
serde = "1.0.149"
serde_json = "1.0.89"
surrealdb-rs = { git = "https://github.com/surrealdb/surrealdb.rs", version = "0.1.0" }
ulid = { version = "1.0.0", features = ["serde"] }
reqwest = { version = "0.11.13", features = ["json"] }
hosting_types = { path = "../hosting_types", version = "*" }
actix-cors = "0.6.4"
env_logger = "0.10.0"
log = "0.4.17"